---
version: '3'
name: online-shopping
services:
   inventory-service:
     image: osk19/online-shopping-inventory-service
     ports:
       - 8082:8082
     environment:
       SERVER_PORT: 8082
       DB_URL: jdbc:postgresql://postgres:5432/postgres
       DB_USERNAME: root
       DB_PASSWORD: root
     depends_on:
       - postgres
     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
       interval: 10s
       timeout: 5s
       retries: 5
     deploy:
       resources:
         limits:
           cpus: '0.5'
           memory: 812M
